apiVersion: v1
kind: ConfigMap
metadata:
  name: opendc-logstash
  namespace: {{ .Values.namespace }}
  labels:
    solution: l1_logging
    product:  logstash
    heritage: {{ .Release.Service | quote }}
    release:  {{ .Release.Name | quote }}
    chart:    "{{ .Chart.Name }}-{{ .Chart.Version }}"
data:
  opendc.conf: |
    input {
      beats {
        port => 5044
      }
    }

    filter {
      if [type] == "kube-pods" {

        mutate {
          rename => ["log", "message"]
        }

        date {
          match => ["time", "ISO8601"]
          remove_field => ["time"]
        }

        grok {
            match => { "source" => "/var/log/containers/%{DATA:pod_name}_%{DATA:namespace}_%{GREEDYDATA:container_name}-%{DATA:container_id}.log" }
            remove_field => ["source"]
        }
      }
    }

    output {
      elasticsearch {
        hosts => ["http://opendc-elasticsearch:9200"]
        index => "opendc-%{+YYYY.MM.dd}"
        document_type => "k8s-pods"
      }
    }