Master:
  Image:    jenkins/jenkins
  ImageTag: 2.79
  Cpu:      500m
  Memory:   512Mi
  ServiceType: ClusterIP
  HostName:    jenkins.opendc.io
  #JMXPort: Use this later to get JMX metrics into Prometheus?

  Ingress:
    Annotations:
      kubernetes.io/tls-acme:      "true"
      kubernetes.io/ingress.class: nginx
  
  #InstallPlugins: