---
alertmanager:
  enabled: false
pushgateway:
  enabled: false
server:
  ingress:
    enabled: true
    hosts:
      - prometheus.opendc.io
    annotations:
      kubernetes.io/tls-acme: "true"
      kubernetes.io/ingress.class: nginx
