apiVersion: v1
kind: Service
metadata:
  name: opendc-keycloak
  namespace: {{ .Values.namespace }}
  labels:
    solution: im1_identity_management
    product:  keycloak
    heritage: {{ .Release.Service | quote }}
    release:  {{ .Release.Name | quote }}
    chart:    "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  selector:
    solution: im1_identity_management
    product:  keycloak
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP