apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: opendc-keycloak
  namespace: {{ .Values.namespace }}
  labels:
    solution: im1_identity_management
    product:  keycloak
    heritage: {{ .Release.Service | quote }}
    release:  {{ .Release.Name | quote }}
    chart:    "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      solution: im1_identity_management
      product:  keycloak
  strategy: {'type': 'Recreate'}
  template:
    metadata:
      labels:
        solution: im1_identity_management
        product:  keycloak
        heritage: {{ .Release.Service | quote }}
        release:  {{ .Release.Name | quote }}
        chart:    "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      containers:
      - name: opendc-keycloak
        image: {{ .Values.keycloak_image }}:{{ .Values.keycloak_tag }}
        imagePullPolicy: {{ default "IfNotPresent" .Values.pullPolicy }}
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        env:
          - name: KEYCLOAK_USER
            value: admin
          - name: KEYCLOAK_PASSWORD
            value: admin
        args:
          - -Dkeycloak.migration.realmName=master
          - -Dkeycloak.migration.action=import
          - -Dkeycloak.migration.strategy=IGNORE_EXISTING
          - -Dkeycloak.migration.provider=singleFile
          - -Dkeycloak.migration.file=/opt/jboss/keycloak/opendc/master-realm.json
          - -Djboss.bind.address=0.0.0.0
        volumeMounts:
          - name: opendc-realm-json
            mountPath: /opt/jboss/keycloak/opendc/
          - name: opendc-keycloak
            readOnly: false
            mountPath: /opt/jboss/keycloak/standalone/data/
        resources:
          limits:
            cpu: 600m
            memory: 500Mi
          requests:
            cpu: 400m
            memory: 500Mi
      volumes:
        - name: opendc-realm-json
          configMap:
            name: opendc-keycloak
        - name: opendc-keycloak
          persistentVolumeClaim:
            claimName: opendc-keycloak
