apiVersion: v1
kind: Service
metadata:
  name: opendc-kibana
  namespace: {{ .Values.namespace }}
  labels:
    solution: l1_logging
    product:  kibana
    heritage: {{ .Release.Service | quote }}
    release:  {{ .Release.Name | quote }}
    chart:    "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  selector:
    solution: l1_logging
    product:  kibana
  ports:
  - name:       ui
    port:       80
    targetPort: ui
    protocol:   TCP