apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: opendc-curator
  namespace: {{ .Values.namespace }}
  labels:
    solution: l1_logging
    product:  curator
    heritage: {{ .Release.Service | quote }}
    release:  {{ .Release.Name | quote }}
    chart:    "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  schedule: 1 0 * * *
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: opendc-curator
            image: bobrik/curator
            args: ["--config", "/etc/config/config.yml", "/etc/config/action_file.yml"]
            volumeMounts:
              - name: opendc-curator
                mountPath: /etc/config
          volumes:
            - name: opendc-curator
              configMap:
                name: opendc-curator
          restartPolicy: OnFailure