apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opendc-elasticsearch
  namespace: {{ .Values.namespace }}
  labels:
    solution: l1_logging
    product:  elasticsearch
    heritage: {{ .Release.Service | quote }}
    release:  {{ .Release.Name | quote }}
    chart:    "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      solution: l1_logging
      product:  elasticsearch
