apiVersion: rook.io/v1alpha1
kind: Cluster
metadata:
  name: rook
  namespace: rook
spec:
  versionTag: master
  dataDirHostPath:
  storage:
    useAllNodes: true
    useAllDevices: false
    storeConfig:
      storeType: filestore
      databaseSizeMB: 1024
      journalSizeMB: 1024