apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: rook-block
   annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: rook.io/block
parameters:
  pool: test