---
server:
  ingress:
    enabled: true
    hosts:
      - grafana.opendc.io
    annotations:
      kubernetes.io/tls-acme: 'true'
      kubernetes.io/ingress.class: nginx

  setDatasource:
    enabled: true
    image: appropriate/curl:latest
    restartPolicy: OnFailure
    datasource:
      name: prometheus
      type: prometheus
      url: http://prometheus-prometheus-server:80
