---
server:
  ingress:
    enabled: true
    installPlugins: grafana-worldmap-panel
    hosts:
      - grafana.opendc.io
    annotations:
      kubernetes.io/tls-acme:      "true"
      kubernetes.io/ingress.class: nginx
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.opendc.io

  setDatasource:
    enabled: true
    image: appropriate/curl:latest
    restartPolicy: OnFailure
    datasource:
      name: prometheus
      type: prometheus
      url: http://prometheus-prometheus-server:80
