---
service:
  type: ClusterIP

ingress:
  enabled: true
  hosts:
    - nexus.opendc.io
  annotations:
    kubernetes.io/tls-acme:      "true"
    kubernetes.io/ingress.class: nginx
  tls:
    - secretName: nexus-tls
      hosts:
        - nexus.opendc.io

persistence:
  size: 50Gi